
networks:
  jetstream:
    external: false
    name: jetstream
  traefik:
    external: false
    name: traefik

services:
  traefik:
    image: traefik:v3.0
    command: |
      --api.insecure
      --providers.docker
      --entrypoints.web.address=:80
      --entrypoints.websecure.address=:443
    restart: unless-stopped
    labels:
      traefik.http.routers.traefik.rule: Host(`local.nathejk.dk`)
      traefik.http.services.traefik.loadbalancer.server.port: 8080
    networks:
    - traefik
    volumes:
    - ./letsencrypt:/letsencrypt
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 127.0.0.1:80:80
    - 127.0.0.1:443:443

  jetstream:
    image: nats:2.10-alpine
    command: -js
    volumes:
    - ./jetstream:/tmp/nats
    networks:
    - jetstream
    ports:
    - 127.0.0.1:4222:4222
    - 127.0.0.1:8222:8222

  nui:
    image: ghcr.io/nats-nui/nui
    volumes:
    - ./nui:/db
    networks:
    - traefik
    ports:
    - 31311
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik
      traefik.http.routers.nui.rule: Host(`jetstream.local.nathejk.dk`)
      traefik.http.services.nui.loadbalancer.server.port: 31311

